name: flutter_onion_architecture
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  auto_mappr_annotation: ^2.1.0
  busenet: ^0.9.1
  cupertino_icons: ^1.0.2
  envied: ^0.5.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.5.0
  json_annotation: ^4.8.1
  mediatr:
    path: ./modules/mediatr/
  path_provider: ^2.1.1

dev_dependencies:
  auto_mappr: ^2.1.1
  build_runner: null
  envied_generator: ^0.5.2
  flutter_driver:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  injectable_generator: ^2.6.2
  json_serializable: ^6.7.1
  mockito: ^5.4.3
  test: ^1.24.3

flutter:
  uses-material-design: true
