builders:
  mapper_builder_json:
    import: "package:mapper_generator/builder.dart"
    builder_factories: ["mapperJsonBuilder"]
    build_extensions: { ".dart": [".mapping.json"] }
    auto_apply: dependents
    runs_before: ["mapper_builder_json|mapper_builder"]
    build_to: cache
  mapper_builder:
    import: "package:mapper_generator/builder.dart"
    builder_factories: ["mapperBuilder"]
    build_extensions: { ".dart": [".mapper.dart"] }
    auto_apply: dependents
    build_to: source
